blueprint:
  name: Home Location Update - Button
  description: >-
    Updates the core Home Assistant location to a device's current 
    location when 'input_button.set_home_location' is pressed.
    
    REQUIRES an 'input_button' helper with the exact
    entity ID: input_button.set_home_location
  domain: automation
  
  input:
    geocoded_sensor:
      name: Geocoded Location Sensor
      description: Select the sensor whose location will be used (e.g., your phone).
      selector:
        entity:
          domain: sensor

mode: single

trigger:
  - platform: state
    entity_id: input_button.set_home_location

variables:
  sensor_entity: !input geocoded_sensor
  loc_attribute: "{{ state_attr(sensor_entity, 'location') or state_attr(sensor_entity, 'Location') }}"

condition:
  # Check if the 'loc_attribute' variable we just created is valid
  - condition: template
    value_template: >-
      {{ loc_attribute is not none and 
         loc_attribute is iterable and 
         loc_attribute | length == 2 }}

action:
  # Use the 'loc_attribute' variable
  - service: homeassistant.set_location
    data:
      latitude: "{{ loc_attribute[0] }}"
      longitude: "{{ loc_attribute[1] }}"